---

- hosts: localhost
  become: true
  vars_files:
    - vars.yml


  tasks:
  ###############################
  # MySQL
  ###############################
  - name: Create and populate database from sql file
    mysql_db: 
      name: all
      state: import
      login_user: root
      login_password: "{{ mysql_root_password }}"
      target: "{{ mysql_import_file }}"

