---

- hosts: localhost
  become: true


  tasks:

  - name: Add the Logstash filter configuration for Kafka topic
    template: src=templates/kafka-input.conf dest=/etc/logstash/conf.d/10-kafka-input.conf

  - name: Add the Logstash output configuration to Elasticsearch
    template: src=templates/elasticsearch-output.conf dest=/etc/logstash/conf.d/20-elasticsearch-output.conf

  - name: Start Logstash
    service: name=logstash state=restarted
